server:
  port: 8082

spring:
  kafka:
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:geoAdapter}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic: ${KAFKA_ADAPTER:msg}

logging:
  level:
    org:
      springframework: ${LOG:info}

myapp:
  data-source: ${SOURCE:hh}
  csv-path-file: "/worldcities.csv"
  hh-path-url: "https://api.hh.ru/areas"